server:
  port: 6001
spring:
  thymeleaf:
    cache: false

paypal:
  mode: sandbox
  client:
    app: Adn3wWJB1AOq4Fij4zKXvk_CSejtZptatvQQk0w5TeDAorxtGUGmelZmlxWVabAW-SXUjcqt8RmLwEmg
    secret: EN4lsFE0_JImUZl2vad3Mvme4R5j5IH_m5oToxafMLsGX_y5OTNAJn3oAhaqyzUg0HB5Kf5Mwd2F0xGq