server:
  port: 2000

spring:
  application:
    name: gtw-crowd-mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/project_crowd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 199564

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.gtw.crowd.entity.po
