server:
  port: 1000



eureka:
  instance:
    hostname: localhost #eurek server instance's name
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #clouster
      #      defaultZone: http://eureka7002.com:7002/eureka/
      #single
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #server:
    #Close the self-protection mechanism to ensure that unavailable services are kicked out in time
    #enable-self-preservation: false
    #eviction-interval-timer-in-ms: 2000