server:
  port: 6001
  servlet:
    context-path: /order
spring:
  application:
    name: gtw-crowd-order
  redis:
    host: 192.168.182.128
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
paypal:
  mode: sandbox
  client:
    app: Adn3wxxxxxxxxx
    secret: EN4lxxxxxxxxxxxx